server:
  port: 8082
  ssl:
    key-store: classpath:server.jks
    key-store-password: XXX
    key-store-type: JKS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/raylee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #password:
logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath*:**/mapping/**/*Mapper.xml