server:
  port: 443
  ssl:
    key-store: classpath:lee1314.com.jks
    key-store-password: ###
    key-store-type: JKS

spring:
  profiles:    active:    - pro
    
  thymeleaf:    cache: false
      
mybatis:
  mapper-locations:  - classpath*:**/mapper/**/*Mapper.xml